version: "3.9"
    
services:
  nano:
    image: magicdan/ros-opencr-aarch64:latest
    network_mode: "host" 
    privileged: true
    environment:
      - "ROS_MASTER_URI=http://192.168.50.180:11311"
    volumes:
      - /dev/:/dev/
    devices:
      - /dev/ttynano:/dev/ttynano
    tty: true
    command: rosrun rosserial_python serial_node.py __name:="nano" _baud:=115200 _port:=/dev/ttynano
    restart: always
    
  opencr:
    image: magicdan/ros-opencr-aarch64:latest
    network_mode: "host" 
    environment:
      - "ROS_MASTER_URI=http://192.168.50.180:11311"
      - "ROS_HOSTNAME=jetsonnano"   
    volumes:
      - /dev/:/dev/
    devices:
      - /dev/ttyopencr:/dev/ttyopencr
    tty: true
    command: rosrun rosserial_python serial_node.py __name:="opencr" _baud:=115200 _port:=/dev/ttyopencr
    restart: always
  
  kinect:
    image: magicdan/ros-kinect-aarch64:latest 
    network_mode: "host" 
    privileged: true
    environment:
      - "ROS_MASTER_URI=http://192.168.50.180:11311"
      - "ROS_HOSTNAME=jetsonnano" 
    volumes:
      - /dev/:/dev/
    devices:
      - /dev/ttykinect:/dev/ttykinect
    tty: true
    command: /catkin_ws/exec.sh
    restart: always
    # roslaunch turtlebot3_gazebo turtlebot3_gazebo_rviz.launch
    # rosrun rviz rviz
    # roslaunch gazebo_ros willowgarage_world.launch
    # rosrun turtlesim turtlesim_node
    # rospack list
    # roslaunch turtlebot3_fake turtlebot3_fake.launch

    # source "/catkin_ws/devel/setup.bash"
  #rosrun rosserial_python serial_node.py __name:="nano" _baud:=115200 _port:=/dev/ttynano