#!/bin/bash

docker run -it --rm --privileged --net=host \
  --volume /dev:/dev \
  --env=ROS_MASTER_URI=http://jetsonagx:11311/ \
  --env=ROS_HOSTNAME=jetsonnano \
  --env=NVIDIA_VISIBLE_DEVICES=all \
  --env=NVIDIA_DRIVER_CAPABILITIES=all \
  --env=DISPLAY \
  --env=QT_X11_NO_MITSHM=1 \
  --runtime=nvidia \
  --env=NVIDIA_VISIBLE_DEVICES=0 \
  --volume /tmp/.X11-unix:/tmp/.X11-unix \
  --volume=/dev/ttykinect:/dev/ttykinect \
  magicdan/ros-kinect-aarch64:latest \
/bin/bash

#/bin/bash
#roslaunch freenect_launch freenect.launch
#/catkin_ws/exec.sh

## proble d'openGL corrigé
#apt-get install mesa-utils

#rosdep install --from-paths src --ignore-src -r -y
# A00363A07046048A