#!/bin/bash

docker run -it --rm --privileged --net=host \
  --env=ROS_MASTER_URI=http://jetsonagx:11311/ \
  --env=ROS_HOSTNAME=jetsonnano \
  --volume=/dev/:/dev/ \
  --volume=/home/dan/temp:/tmp \
  --name nano \
  magicdan/aarch64-ros-noetic-opencr:latest \
  rosrun rosserial_python serial_node.py __name:="nano" _baud:=115200 _port:=/dev/ttyUSB0

# rosrun rosserial_python serial_node.py __name:="nano" _baud:=115200 _port:=/dev/ttyUSB0

 
# /bin/bash
# rosrun rosserial_python serial_node.py _baud:=115200 _port:=/dev/ttyopencr
# rosrun turtlesim turtlesim_node

#### après reboot executer :
#### xhost +local:root

# rostopic pub coupe std_msgs/Empty --once
# rostopic pub fan std_msgs/Empty --once

# sudo chmod 777 /var/run/docker.sock

#  rosrun rosserial_arduino make_libraries.py .