#!/bin/bash

sudo chmod 777 /var/run/docker.sock

docker run -it --rm --privileged --net=host \
  --env=ROS_MASTER_URI=http://jetsonagx:11311/ \
  --env=ROS_HOSTNAME=jetsonnano \
  --name roscore \
magicdan/aarch64-ros-noetic-base:latest \
roscore