#!/bin/bash

docker run -it --rm --privileged --net=host \
  -v /dev/input/js0:/dev/input/js0 \
  --env=ROS_MASTER_URI=http://jetsonagx:11311/ \
  --env=ROS_HOSTNAME=jetsonnano \
  --name teleop \
  magicdan/aarch64-ros-noetic-teleop:latest \
  /bin/bash

#  /bin/bash

# rosrun teleop_twist_keyboard teleop_twist_keyboard.py