#!/bin/bash

xhost +si:localuser:root 
sudo chmod 777 /var/run/docker.sock

docker run -it --rm --privileged --net=host \
    --env=ROS_MASTER_URI=http://msi:11311/ \
    --env=ROS_HOSTNAME=msi \
    --env=NVIDIA_VISIBLE_DEVICES=all \
    --env=NVIDIA_DRIVER_CAPABILITIES=all \
    --env=DISPLAY \
    --env=QT_X11_NO_MITSHM=1 \
    --runtime=nvidia \
    --env=NVIDIA_VISIBLE_DEVICES=0 \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
    --volume /home/dan/catkin_ws:/catkin_ws \
    --volume /dev:/dev \
magicdan/msi-ros-noetic-full \
/bin/bash

# /bin/bash
# rosrun rosserial_python serial_node.py _baud:=115200 _port:=/dev/ttyACM0
# rosrun turtlesim turtlesim_node

#### après reboot executer :
#### xhost +local:root

# rostopic pub coupe std_msgs/Empty --once
# rostopic pub fan std_msgs/Empty --once

# sudo chmod 777 /var/run/docker.sock