#!/bin/bash

sudo chmod 777 /var/run/docker.sock

docker run -it --rm --privileged --net=host \
  --env=ROS_MASTER_URI=http://msi:11311/ \
  --env=ROS_HOSTNAME=msi \
  --name roscore \
  magicdan/msi-ros-noetic:latest \
  roscore