FROM magicdan/ros-base-aarch64:latest

USER root

RUN apt-get update && apt-get install ros-melodic-turtlesim -y --no-install-recommends 

RUN apt-get install ros-melodic-rosse* -y --no-install-recommends nano